// Generated by CoffeeScript 1.6.3
(function() {
  var Instagram, jp2a, moment, renderImage, _;

  _ = require('underscore');

  Instagram = require('instagram-node-lib');

  jp2a = require('jp2a');

  moment = require('moment');

  Instagram.set('client_id', 'b8b6e83a5194471d936670c484375a5d');

  Instagram.set('client_secret', '7a56b096833d41ff98f55369c837ef0d');

  Instagram.media.popular({
    complete: function(photos) {
      return _.each(photos, function(photo) {
        var author, dateStr, url;
        author = photo.user.username;
        url = photo.images.standard_resolution.url;
        dateStr = moment(photo.created_time).fromNow();
        return renderImage(url, author, dateStr);
      });
    }
  });

  renderImage = function(url, author, dateStr) {
    return jp2a([url, "--width=75", "--background=dark", "--color", "-b"], function(asciiArt) {
      console.log(asciiArt);
      console.log("By: " + author);
      return console.log(dateStr);
    });
  };

}).call(this);
